// File generated by Gemini for FonTakip
// Use 'flutterfire configure' to regenerate this file with actual Windows/Web credentials if needed.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5JrQIL3bymGG_Apr_MAc0Nj8HN_xdt04',
    appId: '1:575790058034:web:e5c60479a1791c55540a2b',
    messagingSenderId: '575790058034',
    projectId: 'fonttakip',
    authDomain: 'fonttakip.firebaseapp.com',
    storageBucket: 'fonttakip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwO2YiapuJkq6IQfwIcpz2Djt5TlIzuww',
    appId: '1:575790058034:android:f9beda73535ca6f8540a2b',
    messagingSenderId: '575790058034',
    projectId: 'fonttakip',
    storageBucket: 'fonttakip.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyE5EwBYrAqqNmZt6REOFm7aX6baF_ak',
    appId: '1:575790058034:ios:ecd4e584a508b48b540a2b',
    messagingSenderId: '575790058034',
    projectId: 'fonttakip',
    storageBucket: 'fonttakip.firebasestorage.app',
    androidClientId: '575790058034-7kq4704ifd4q2790ksdtfitq38odheks.apps.googleusercontent.com',
    iosClientId: '575790058034-c8lfrfn33ists69qsc4fscoseolbovcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontakip',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyE5EwBYrAqqNmZt6REOFm7aX6baF_ak',
    appId: '1:575790058034:ios:ecd4e584a508b48b540a2b',
    messagingSenderId: '575790058034',
    projectId: 'fonttakip',
    storageBucket: 'fonttakip.firebasestorage.app',
    androidClientId: '575790058034-7kq4704ifd4q2790ksdtfitq38odheks.apps.googleusercontent.com',
    iosClientId: '575790058034-c8lfrfn33ists69qsc4fscoseolbovcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5JrQIL3bymGG_Apr_MAc0Nj8HN_xdt04',
    appId: '1:575790058034:web:05f9050c84001d5a540a2b',
    messagingSenderId: '575790058034',
    projectId: 'fonttakip',
    authDomain: 'fonttakip.firebaseapp.com',
    storageBucket: 'fonttakip.firebasestorage.app',
  );
}
